### ISSUE TITLE
Milestone 3 to-dos

### ISSUE THREAD

**Issue by mdkbmi** [UBC-MDS/Car_Evaluation_Analysis#44]
* Abstract code from `.ipynb` file
* Convert `.ipynb` file to `.qmd`
* Edit `.qmd` file such that it only narrates the analysis (no computation codes inside)
* Update environment and dependencies

**Comment by mdkbmi** [comment]
For code abstraction
* Import, validation, train/test split
* EDA
* Choosing ML model
* Hyperparameter tuning

**Comment by davyxuximin** [comment]
For narrate analysis and visualization and formatting qmd:

- Use markdown headers and Quarto configuration so that a table of contents will be created when the document is rendered.

- Add correctly formatted inline BibTeX references so that a nicely formatted reference list will be present at the end of the document.

-  Edit the figure formatting so that Quarto:
automatically numbers them,
has a label for easy cross referencing, and
controls the figure sizes so the figures are not too big.

- Add a table description argument so that they are automatically numbered by Quarto and use cross referencing to link to the table when it is discussed in the text.

- Edit the narrative so it uses cross-referencing to refer to the figures and tables instead of having their reference hardcode the figure and table numbers.

- Replace any hard-coded values in the Quarto report narrative text with inline Quarto code, so that the text will be automatically updated with the correct value.

- Change the code chunk options so that no code is viewable in the rendered report, just the code outputs where needed (e.g., figures and tables).
